---
mobSpawn:
  modifiable: true
  item:
    material: "ZOMBIE_HEAD"
    amount: 1
    displayName: "&b&lMob Spawn"
    headData: null
    headOwner: null
    headOwnerUUID: null
    lore:
    - "&7Laissez les zombie spawn sur votre île."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 10
  defaultValue: "true"
leafDecay:
  modifiable: true
  item:
    material: "OAK_LEAVES"
    amount: 1
    displayName: "&b&lLeaf Decay"
    headData: null
    headOwner: null
    headOwnerUUID: null
    lore:
    - "&7Laissez les feuilles pourrir sur votre île."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 11
  defaultValue: "true"
weather:
  modifiable: true
  item:
    material: "SNOWBALL"
    amount: 1
    displayName: "&b&lMétéo de l'île"
    headData: null
    headOwner: null
    headOwnerUUID: null
    lore:
    - "&7Changer le temps de votre île."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 12
  defaultValue: "DEFAULT"
time:
  modifiable: true
  item:
    material: "CLOCK"
    amount: 1
    displayName: "&b&lHeure de l'île"
    headData: null
    headOwner: null
    headOwnerUUID: null
    lore:
    - "&7Changez l’heure de votre île."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 13
  defaultValue: "DEFAULT"
endermanGrief:
  modifiable: true
  item:
    material: "ENDER_PEARL"
    amount: 1
    displayName: "&b&lEnderman Grief"
    headData: null
    headOwner: null
    headOwnerUUID: null
    lore:
    - "&7Laisse Enderman rammasser des block sur ton île."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 14
  defaultValue: "true"
liquidFlow:
  modifiable: true
  item:
    material: "WATER_BUCKET"
    amount: 1
    displayName: "&b&lEcoulement du liquide"
    headData: null
    headOwner: null
    headOwnerUUID: null
    lore:
    - "&7Laissez l’eau et la lave couler sur votre île."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 15
  defaultValue: "true"
tntDamage:
  modifiable: true
  item:
    material: "TNT"
    amount: 1
    displayName: "&b&lTnT Damage"
    headData: null
    headOwner: null
    headOwnerUUID: null
    lore:
    - "&7Laissez le TnT exploser sur votre île."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 16
  defaultValue: "true"
fireSpread:
  modifiable: true
  item:
    material: "FLINT_AND_STEEL"
    amount: 1
    displayName: "&b&lFire Spread"
    headData: null
    headOwner: null
    headOwnerUUID: null
    lore:
    - "&7Laissez le feu se propager sur votre île."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 19
  defaultValue: "true"
